language: smalltalk
sudo: false

branches:
  except:
    - windows
    - /^v[0-9]/

install:
  # Move cache directory if it exists
  - "[[ ! -d ${SMALLTALK_CI_CACHE} ]] || mv ${SMALLTALK_CI_CACHE} $(pwd)"

script: bin/smalltalkci --self-test

aliases:
  - &ensure-smalltalkci-can-fail
    smalltalk_config: .smalltalk_fail.ston
    script: "! bin/smalltalkci --self-test"
  - &with-gemstone-cache-enabled
    cache:
      directories:
        - ${SMALLTALK_CI_CACHE}

jobs:
  include:
    - stage: "Prioritized jobs"
      smalltalk: Squeak-5.1
    - smalltalk: Squeak-trunk
    - smalltalk: Pharo64-stable
    - smalltalk: Pharo64-alpha
    - smalltalk: Pharo-stable
    - smalltalk: Pharo-alpha
    - smalltalk: GemStone-3.3.2
      env: GSCI_CLIENTS="Pharo-5.0 Pharo-4.0 Pharo-3.0"
      <<: *with-gemstone-cache-enabled

    - language: bash
      smalltalk:
      sudo: false
      script: tests/all_tests.sh

    - smalltalk: Squeak-5.1
      os: osx
    - smalltalk: Squeak-trunk
      os: osx
    - smalltalk: Pharo-stable
      os: osx
    - smalltalk: Pharo-alpha
      os: osx
    - smalltalk: GemStone-3.3.2
      os: osx
      <<: *with-gemstone-cache-enabled

    - smalltalk: Squeak-5.1
      <<: *ensure-smalltalkci-can-fail
    - smalltalk: Pharo-stable
      <<: *ensure-smalltalkci-can-fail
    - smalltalk: GemStone-3.3.2
      <<: *ensure-smalltalkci-can-fail
      env: GSCI_CLIENTS="Pharo-5.0 Pharo-3.0" # latest and oldest clients
      <<: *with-gemstone-cache-enabled

    - stage: "Linux jobs"
      smalltalk: Squeak-5.0
    - smalltalk: Squeak-4.6
    - smalltalk: Squeak-4.5
    - smalltalk: Pharo64-7.0
    - smalltalk: Pharo64-6.1
    - smalltalk: Pharo64-6.0
    - smalltalk: Pharo-7.0
    - smalltalk: Pharo-6.0
    - smalltalk: Pharo-6.1
    - smalltalk: Pharo-5.0
    - smalltalk: Pharo-4.0
    - smalltalk: Pharo-3.0
    - smalltalk: Moose-trunk
    # - smalltalk: Moose-6.1   # identical to Moose-trunk
    - smalltalk: Moose-6.0
    - smalltalk: GemStone-3.2.15
      <<: *with-gemstone-cache-enabled
    - smalltalk: GemStone-3.1.0.6
      <<: *with-gemstone-cache-enabled

    - stage: "Mac jobs"
      smalltalk: Squeak-5.0
      os: osx
    - smalltalk: Squeak-4.6
      os: osx
    - smalltalk: Squeak-4.5
      os: osx
    - smalltalk: Pharo-7.0
      os: osx
    - smalltalk: Pharo-6.0
      os: osx
    - smalltalk: Pharo-6.1
      os: osx
    - smalltalk: Pharo-5.0
      os: osx
    - smalltalk: Pharo-4.0
      os: osx
    - smalltalk: Pharo-3.0
      os: osx      
#    - smalltalk: GemStone-3.2.14
#      os: osx
##      env: GSCI_DEVKIT_BRANCH=dev  # only use for development
#    - smalltalk: GemStone-3.1.0.6
#      os: osx
##      env: GSCI_DEVKIT_BRANCH=dev  # only use for development

  allow_failures:
    - smalltalk: Squeak-trunk
    - smalltalk: Pharo-alpha
    - smalltalk: Pharo64-alpha
    - smalltalk: Moose-trunk
    - smalltalk: Moose-6.0
  fast_finish: true
